### ISSUE TITLE
Jamboard (SERVICE)

### ISSUE THREAD

**Issue by FrankVan1982** [edvinlinden/killedby.tech#79] opened 2023-09-30 18:46 UTC
**Product name:** Jamboard
**Company:** Google
**Description:** Jamboard was a digital 4K touchscreen whiteboard device that allowed to collaborate using Google Workspace services. It will be over 7 years old.
**Type of product:** Service
**Release date:** 2017
**Discontinued date:** September 2024
**Source:** Google email that comunicate the end-of-life of Jamboard, and [https://en.wikipedia.org/wiki/Jamboard](https://en.wikipedia.org/wiki/Jamboard)

**Comment by edvinlinden** [comment] 2023-10-01 18:04
Closing as duplicate of #80

**Closed by edvinlinden** 2023-10-01 18:04 UTC
